FROM node:20-alpine

WORKDIR /usr/src/app

ENV TZ=Asia/Bangkok

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json ./
COPY next.config.js ./

RUN npm install --legacy-peer-deps --ignore-scripts

COPY . /usr/src/app
RUN mv .env.dev .env

RUN npm run build

EXPOSE 3000

CMD ["npm","run", "start"]
